### PR TITLE
Dynamic segment sizing

### PR DESCRIPTION
**Pull request by maxcampolo**
This PR adds support for dynamic segment sizing based on the content size of the segment. Instead of fixing the number of visible cells, each cell is a different size based on the length of its title (plus the image in the case of the imageBefore and imageAfter styles). The way to use it is to pass a SegmentioPosition option in the initializer, either .dynamic or .fixed(maxVisibleItems: 3). The fixed option is the same behavior that exists currently. 
Changes:
- Add SegmentioPosition enum with fixed and dynamic options
- Replace maxVisibleItems with maxVisibleItems property in fixed case eg. .fixed(maxVisibleItems: 3)
- Update Points extension with more parameters for dynamic layout calculations
- Replace scrollToItem at index path calls with scrollRectToVisible in scrollToItemAtContext
- Update itemInSuperview method for dynamic and fixed position cases
- Separated method for calculating segment width
- Added width property to SegmentioItem
- Update example project

There are quite a few changes in this PR so if you want anything updated, changed, done differently, etc. please let me know and I’m happy to do it!

Ty for the awesome framework.

### CODE REVIEW

**Comment by rmvz3** [comment]
@maxcampolo How can I download your version? I've downloaded your fork but it seems it doesn't include these changes

**Comment by maxcampolo** [comment]
Hey @rmvz3 all these changes are in the branch called `fix/label-layout`. I'll just merge it over to my master eventually but you can use that branch for now.

**Comment by rmvz3** [comment]
@maxcampolo I've just realized. That's why I deleted my question.  My fault ¯\_(ツ)_/¯

Thank you

**Comment by adrianodiasx93** [comment]
No love for this PR?
Any plans to merge this with the master?

**Comment by Tykhonkov** [comment]
Hello @maxcampolo , thank you for a great work. I have tested your PR and found some issues with cell width

 Preview

and also with wrong positioning of indicator

 Preview

Can you fix them?

**Comment by maxcampolo** [comment]
@Tykhonkov sure thing let me look at this. The first image looks correct, the cell sizes based on the size of the content contained in it, using the image width if there is no label. The second image indicator position is definitely wrong. Any specifics on reproducing? Thanks!

**Comment by maxcampolo** [comment]
@Tykhonkov I pushed some updates that should fix these issues. I also updated the example project so to test you can just add the `segmentioPosition: .dynamic` option to the `SegmentioBuilder` call in `ViewDidAppear(_:)` of `ExampleViewController`. 
image

Thanks for reviewing!

**Comment by Tykhonkov** [comment]
ill test it

**Comment by NSMyself** [comment]
Apologies for bothering, but may I ask if this PR is going to be merged any time soon? 
I'll just use the specific branch for now in any case

**Comment by AndrewPetrov** [comment]
@maxcampolo Could you please update your request by pulling last changes in our master branch ?

**Comment by maxcampolo** [comment]
@AndrewPetrov okay I've merged the latest from master and updated the PR. Thanks for reviewing!

**Comment by AndrewPetrov** [comment]
@maxcampolo I'm sorry but your fix still has some issues with highlighting http://joxi.ru/gmvjlP0FLgy41m

**Comment by maxcampolo** [comment]
@AndrewPetrov sorry about that! This was just a bug calculating the position in the .fixed segment width option. Turned out to be misplaced `if` statement brackets. Should be fixed now. Thanks!

**Comment by batjo** [comment]
Could this please be merged?

**Pull request merged**
