### PR TITLE
title label text scale fixes

### PR DESCRIPTION
**Pull request by serhii-londar**

### CODE REVIEW

**Comment by Tykhonkov** [comment]
Hi @serhii-londar , can you describe your PR?

**Comment by serhii-londar** [comment]
Hi @Tykhonkov . I added font scaling for labels. In case when we have static segmentio cell size it shows text with dots (for example: Featured as Featur...). So I added font scaling for labels to show fulltext with lower font size.

**Comment by AndrewPetrov** [comment]
@serhii-londar Thanks for work, could you please clean up your PR from unnecessary colorSpace transformation and so on and leave only valuable changes?

**Comment by serhii-londar** [comment]
@DarthRumata I removed all non valuable changes!

**Pull request merged**
